
// const basicLanguage = {
//   homeLinkBtn: "Home",
//   authLinkBtn: "Authorize",
//   setsLinkBtn: "Settings",
//   login: "Login",
//   register: 'Register',
//   yourName: 'Your name',
//   submit: 'Submit',
//   confirm: 'Confirm',
//   greetings: 'Hello there',
//   firstTimeRate: 'You have an honor to be first to rate this place!',
//   placeRatingPrefix: 'This place has rating of',
//   placeAmountPrefix: 'Rated',
//   placeAmountNumberEnds1: 'time',
//   placeAmountNPostfix: 's',
//   push: 'Push',
//   commentPlacehol: 'any comments?'
// }

import { appThemes } from "./config"


const rus = {
  homeLinkBtn: "Главная",
  authLinkBtn: "Логин",
  profile: "Профиль",
  theme: "Тема",
  friends: "Друзья",
  routes: "Маршруты",
  language: "Язык",
  aboutUs: "О нас",
  setsLinkBtn: "Настройки",
  login: "Логин",
  logout: 'Выйти',
  register: 'Регистрация',
  yourLogin: 'Ваш логин',
  userName: 'Имя пользователя',
  yourPword: 'Ваш пароль',
  secretQuestion: 'Секретный вопрос',
  secretHint: 'Для восстановления пароля',
  secterAnswer: 'Ответ на секрет',
  secretValidation: 'Вы указали вопрос, укажите и ответ',
  secretReplica: 'Но это не я написал вопрос!',
  secretReplica2: 'А ответ нам всё равно нужен',
  fillRequiredFields: 'Заполните необходимые поля',
  secretExample: 'Имя, которое вы тайно ненавидите',
  submit: 'Отправить',
  confirm: 'Подтвердить',
  greetings: 'Привет',
  firstTimeRate: 'Вам выпала честь первым оценить это место!',
  placeRatingPrefix: 'Общий рейтинг',
  placeAmountPrefix: 'Это место оценили',
  placeAmountNumberEnds1: 'раз',
  placeAmountEndsMultiple: 'раза',
  push: 'Нажать',
  commentPlacehol: 'есть комментарии?',
  rating: 'Ваша оценка',
  bestRating: 'Замечательно',
  worstRating: 'Ужасно',
  reviews: 'Отзывы',
  noComments: 'Без комментариев',
  searchPHolder: 'Найти',
  newFeature: 'Новый объект на карте',
  newFeaturePHolder: 'Адрес или название места',
  drawPromptHeader: 'Режим рисования',
  drawPrompt: 'Завершите создание, дважды нажав на последнюю точку полигона',
  level: 'уровень',
  acceptDefault: 'принять',
  cancelDefault: 'отклонить',
  rateZeroModal: 'Действительно поставить оценку 0?',
  toMain: 'На главную',
  menu: 'Меню',
  pickTheme: 'Выберете тему',
  apply: 'Применить',
  password: 'Пароль',
  field: 'поле',
  tooLong: 'слишком длинное',
  [appThemes[0]]: 'Стандартная',
  [appThemes[1]]: 'Тёмная',
  [appThemes[2]]: 'Black&White',
  [appThemes[3]]: 'Чертёжная',
  successfullReg: 'Успешная регистрация!', 
  errorReg: 'Возникла ошибка при регистрации', 
  errCode: 'код ошибки',
  loginOccupied: 'Логин уже занят',
  wrongAuth: 'Неверные данные для входа',
  editProfile: 'Редактирование профиля',
  successfulUpdate: 'Успешное обновление',
  secretChallenge: 'Вам нужно ответить на секретный вопрос, чтобы изменить пароль',
}

// export const TEXT = window.APPTEXT || basicLanguage
export const TEXT = rus